-- AlterTable
ALTER TABLE "Session" ADD COLUMN IF NOT EXISTS "isSwap" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Session" ADD COLUMN IF NOT EXISTS "giveSkill" TEXT;
ALTER TABLE "Session" ADD COLUMN IF NOT EXISTS "takeSkill" TEXT;
ALTER TABLE "Session" ADD COLUMN IF NOT EXISTS "proposerId" TEXT;
